name: "Pull request"
description: "Create a pull request."
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the pull request."
      placeholder: "This pull request does X."
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "If you have any other relevant information, write it here."
      placeholder: "The bug didn't start to occur until X."
  
