name: "Feature request"
description: "Request a new feature."
labels: ["enhancement"]
assignees: ["Lakuna"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the feature as concisely as possible."
      placeholder: "I wish that X."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: "Possible solution"
      description: "If you have any ideas about how this feature might be implemented, write them here."
      placeholder: "It might be possible to X by Y."
  - type: textarea
    id: details
    attributes:
      label: "Details"
      description: "If you have any other relevant information, write it here."
      placeholder: "This feature might X."
  
