name: Request a feature
description: Request a new feature.
labels:
  - enhancement
assignees:
  - Lakuna
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature as concisely as possible.
      placeholder: Description of the feature.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Possible Solution
      description: If you have any ideas about how this feature might be implemented, write them here.
      placeholder: Possible solution.
  - type: textarea
    id: details
    attributes:
      label: Details
      description: If you have any other relevant information, write it here.
      placeholder: Additional information.
